spring:
  main:
    allow-circular-references: true
  application:
    name: user-service
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:spring_assignments;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  sql:
    init:
      platform: h2

server:
  port: 9001

jwt:
  token:
    header: X-HAN-DEMAND-AUTH
    issuer: N_GOLO_KANG_TAE
    client-secret: BBAL_RAL_RA_RAL_RA
    expiry-seconds: 0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # eureka 서버로부터 인스턴스들의 정보를 주기적으로 가져올 것인지 설정. (갱신 된 정보를 받겠다.)
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka