server:
  port: 8001

spring:

  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: testpw

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 853188067648-p2v26huhfrd5tsrd2d9093gude1s51sq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

eureka:
  client:
    fetch-registry: false #true
    register-with-eureka: false #true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.handemand.userservice: debug
