server:
  port: 8001

spring:

  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: testpw

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:

          google:
            client-id: 853188067648-p2v26huhfrd5tsrd2d9093gude1s51sq.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

          naver:
            client-id: MyawfexdYFPBtAXzPXU6
            client-secret: DFeK6VFdBX
            scope:
            - name
            - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8001/login/oauth2/code/naver

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response # 회원정보를 response 필드에 json 으로 응답.

eureka:
  client:
    fetch-registry: false #true
    register-with-eureka: false #true
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.handemand.userservice: debug

token:
  expiration_time: 3600000
  secret: N_GOLO_KANG_TAE_SAN